CC=g++
LIBS = -lm -lrt 

OPT_Debug= -Wall -g -O2

CFLAGS = -DMPU6050 -DMPU_DEBUG -I../libs/

LIB=mpu6050.a
OBJ=mpu6050.o inv_mpu_lib/inv_mpu.o inv_mpu_lib/inv_mpu_dmp_motion_driver.o
#CXXFLAGS = -DDMP_FIFO_RATE=1

ALL=$(LIB)

all: $(ALL)

$(LIB): $(OBJ)

clean:
	rm -rf *.o *~ *.mod
	rm -rf inv_mpu_lib/*.o
	rm -rf $(LIB)
